In [18]:
import pandas as pd

In [21]:
df = pd.read_csv('futebol.csv')

In [22]:
df.head()

,ano_campeonato,data,rodada,estadio,arbitro,publico,publico_max,time_mandante,time_visitante,tecnico_mandante,...,chutes_bola_parada_mandante,chutes_bola_parada_visitante,defesas_mandante,defesas_visitante,impedimentos_mandante,impedimentos_visitante,chutes_mandante,chutes_visitante,chutes_fora_mandante,chutes_fora_visitante
0,2005,2005-10-08,31,Estádio Durival Britto e Silva,NaN,NaN,NaN,Paraná,Fluminense,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2005,2005-04-23,1,Estádio Durival Britto e Silva,NaN,NaN,NaN,Paraná,Goiás EC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2005,2005-08-21,21,Estádio Durival Britto e Silva,NaN,NaN,NaN,Paraná,Vasco da Gama,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2005,2005-08-28,23,Estádio Durival Britto e Silva,NaN,NaN,NaN,Paraná,São Paulo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2005,2005-06-26,9,Estádio Olímpico Nilton Santos,NaN,NaN,NaN,Botafogo,Figueirense FC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df.columns

Index(['ano_campeonato', 'data', 'rodada', 'estadio', 'arbitro', 'publico',
       'publico_max', 'time_mandante', 'time_visitante', 'tecnico_mandante',
       'tecnico_visitante', 'colocacao_mandante', 'colocacao_visitante',
       'valor_equipe_titular_mandante', 'valor_equipe_titular_visitante',
       'idade_media_titular_mandante', 'idade_media_titular_visitante',
       'gols_mandante', 'gols_visitante', 'gols_1_tempo_mandante',
       'gols_1_tempo_visitante', 'escanteios_mandante', 'escanteios_visitante',
       'faltas_mandante', 'faltas_visitante', 'chutes_bola_parada_mandante',
       'chutes_bola_parada_visitante', 'defesas_mandante', 'defesas_visitante',
       'impedimentos_mandante', 'impedimentos_visitante', 'chutes_mandante',
       'chutes_visitante', 'chutes_fora_mandante', 'chutes_fora_visitante'],
      dtype='object')

In [24]:
df = df[['data', 'estadio', 'publico']]

df

            data                                      estadio  publico
0     2005-10-08               Estádio Durival Britto e Silva      NaN
1     2005-04-23               Estádio Durival Britto e Silva      NaN
2     2005-08-21               Estádio Durival Britto e Silva      NaN
3     2005-08-28               Estádio Durival Britto e Silva      NaN
4     2005-06-26               Estádio Olímpico Nilton Santos      NaN
...          ...                                          ...      ...
8448  2017-10-15  Estádio Municipal Paulo Machado de Carvalho  26833.0
8449  2017-10-22  Estádio Municipal Paulo Machado de Carvalho  32965.0
8450  2017-10-28  Estádio Municipal Paulo Machado de Carvalho  40004.0
8451  2017-11-09  Estádio Municipal Paulo Machado de Carvalho  35037.0
8452  2017-11-19  Estádio Municipal Paulo Machado de Carvalho  25771.0

[8453 rows x 3 columns]

In [31]:
df = df.dropna()

df

            data                                      estadio  publico
418   2016-09-15               Estádio Olímpico Nilton Santos  11883.0
419   2016-09-25      Estádio Estadual Kléber José de Andrade  13780.0
420   2016-10-09  Estádio Municipal Paulo Machado de Carvalho  21773.0
421   2016-10-23               Estádio Jornalista Mário Filho  54250.0
422   2016-10-13   Estádio General Sílvio Raulino de Oliveira   9008.0
...          ...                                          ...      ...
8448  2017-10-15  Estádio Municipal Paulo Machado de Carvalho  26833.0
8449  2017-10-22  Estádio Municipal Paulo Machado de Carvalho  32965.0
8450  2017-10-28  Estádio Municipal Paulo Machado de Carvalho  40004.0
8451  2017-11-09  Estádio Municipal Paulo Machado de Carvalho  35037.0
8452  2017-11-19  Estádio Municipal Paulo Machado de Carvalho  25771.0

[6731 rows x 3 columns]

In [49]:
df_2017 = df[df['data'].dt.year == 2017]

In [50]:
df.columns

Index(['data', 'estadio', 'publico'], dtype='object')

In [53]:
df['data'] = pd.to_datetime(df['data'], dayfirst=True)

In [55]:
df = df[df['data'].dt.year == 2017]

In [56]:
df = df[['data', 'estadio', 'publico']]

df

           data                                      estadio  publico
8073 2017-05-21                                  Arena Condá  10323.0
8074 2017-05-30                                  Arena Condá   6188.0
8075 2017-06-09                                  Arena Condá  14403.0
8076 2017-06-15                                  Arena Condá  10033.0
8077 2017-06-18                                  Arena Condá  11603.0
...         ...                                          ...      ...
8448 2017-10-15  Estádio Municipal Paulo Machado de Carvalho  26833.0
8449 2017-10-22  Estádio Municipal Paulo Machado de Carvalho  32965.0
8450 2017-10-28  Estádio Municipal Paulo Machado de Carvalho  40004.0
8451 2017-11-09  Estádio Municipal Paulo Machado de Carvalho  35037.0
8452 2017-11-19  Estádio Municipal Paulo Machado de Carvalho  25771.0

[380 rows x 3 columns]

In [57]:
df.sort_values('publico', ascending=False).head(10)

           data                          estadio  publico
8363 2017-09-24  Estádio Cícero Pompeu de Toledo  61142.0
8365 2017-12-03  Estádio Cícero Pompeu de Toledo  60485.0
8361 2017-08-13  Estádio Cícero Pompeu de Toledo  56052.0
8151 2017-06-25                  Arena do Grêmio  54022.0
8360 2017-08-04  Estádio Cícero Pompeu de Toledo  53635.0
8359 2017-07-25  Estádio Cícero Pompeu de Toledo  51511.0
8310 2017-05-13   Estádio Jornalista Mário Filho  50220.0
8180 2017-11-05                Neo Química Arena  46493.0
8183 2017-11-26                Neo Química Arena  46369.0
8182 2017-11-16                Neo Química Arena  46189.0

In [61]:
maior_publico = df['publico'].max()
menor_publico = df['publico'].min()

print(f"Maior público: {maior_publico}")
print(f"Menor público: {menor_publico}")

Maior público: 61142.0
Menor público: 0.0

In [62]:
df.loc[df['publico'].idxmin()]

data        2017-07-16 00:00:00
estadio    Estádio São Januário
publico                     0.0
Name: 8200, dtype: object

In [63]:
top_10 = df.sort_values('publico', ascending=False).head(10)

In [64]:
top_10.to_csv('top_10_publicos.csv', index=False)

In [66]:
maior_publico = df.loc[[df['publico'].idxmax()]]

In [68]:
menor_publico = df.loc[[df['publico'].idxmin()]]

In [69]:
maior_publico.to_csv('maior_publico_2017.csv', index=False)

In [70]:
menor_publico.to_csv('menor_publico_2017.csv', index=False)